insert into "user" (email, nama, alamat, password, role) values ('dadu@daduhotel.com', 'Dadu', '95 Mendota Street', 'QQ6ZxmJ1', 'DA');
insert into "user" (email, nama, alamat, password, role) values ('wwillis0@example.com', 'William Willis', '95 Mendota Street', 'QQ6ZxmJ1', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('rnguyen1@google.nl', 'Raymond Nguyen', '104 American Ash Trail', 'CGu53QeojT', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('bhanson2@nymag.com', 'Billy Hanson', '80175 Acker Trail', 'BEtV8my', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('kkennedy3@wikipedia.org', 'Kenneth Kennedy', '078 Melrose Court', 'USNQ0N5aIK', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('rriley4@washingtonpost.com', 'Raymond Riley', '7 Bobwhite Pass', 'akZ2VAkpjcp', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('ahudson5@bbb.org', 'Andrew Hudson', '5 Annamark Hill', 'BuPVBM9G', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('shill6@businesswire.com', 'Susan Hill', '085 Dorton Avenue', 'eF3a0tbtihKR', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('pdixon7@mozilla.org', 'Pamela Dixon', '38 Bluejay Trail', 'VYRwEf0Orov', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('sgomez8@wordpress.org', 'Shawn Gomez', '29 Northport Trail', 'lAN4wk7', 'MG');
insert into "user" (email, nama, alamat, password, role) values ('rknight0@seesaa.net', 'Rebecca Knight', '72125 Northport Pass', 'T3yftxQB1j8', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('rhart1@51.la', 'Ryan Hart', '491 Columbus Way', 'B96HLsIm', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('pmedina2@ning.com', 'Pamela Medina', '3518 Kropf Circle', 'VfkYOiH4', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('eross3@vk.com', 'Ernest Ross', '1 Park Meadow Park', 'C14F1Qi', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('kriley4@bandcamp.com', 'Karen Riley', '07643 Independence Street', 'tKfmGA3Xd', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('jgray5@pcworld.com', 'Justin Gray', '946 Killdeer Point', 'wfnOjn', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('bmason6@ning.com', 'Bobby Mason', '242 Farwell Circle', 's1be5XPP3E3', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('tmyers7@slashdot.org', 'Timothy Myers', '6483 Merchant Point', 'SEcX5K', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('pwallace8@miibeian.gov.cn', 'Phyllis Wallace', '8 Esker Plaza', 'PVXPwGl', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('rsmith9@gnu.org', 'Roy Smith', '04 Pennsylvania Pass', 'ifVuZue', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('lwrighta@techcrunch.com', 'Larry Wright', '09 Algoma Street', 'J2HDInVpum', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('plopezb@google.com.au', 'Philip Lopez', '0 Eastlawn Road', 'IPbHF4VQS72o', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('gortizc@posterous.com', 'George Ortiz', '1099 Ilene Lane', 'gQj6Z0V1Xs', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('ecolemand@auda.org.au', 'Emily Coleman', '733 Blackbird Pass', 'ELCjATzD', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('sportere@addthis.com', 'Stephen Porter', '56 Pond Lane', 'YpfCGpXoOxU', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('abishopf@mysql.com', 'Ashley Bishop', '82079 West Court', '7ooYsv6M', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('ggrantg@shutterfly.com', 'George Grant', '222 Pond Drive', 'TkUjwBCqq', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('jhansenh@sun.com', 'Jonathan Hansen', '74565 Pierstorff Parkway', 'ncvNiEl', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('dgordoni@nyu.edu', 'Debra Gordon', '3471 Crowley Park', 'uK61Jy55uQT', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('achapmanj@gizmodo.com', 'Anna Chapman', '17984 Huxley Crossing', 'ElYzvyVwufK', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('mallenk@nature.com', 'Matthew Allen', '07594 3rd Park', 'p2tVX6v0pJt', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('mtorresl@usgs.gov', 'Melissa Torres', '1203 Harper Park', 'dKR8N3', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('cthomasm@friendfeed.com', 'Cheryl Thomas', '1 Lyons Lane', 'Kn6GgZFI', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('jmartinn@simplemachines.org', 'Johnny Martin', '30156 Service Junction', 'hsrlDgBTze', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('kgonzaleso@thetimes.co.uk', 'Kathleen Gonzales', '49 Thompson Center', 'V19jGx2', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('jbrooksp@posterous.com', 'Julie Brooks', '6 Express Pass', '4QAeuWaVIZ', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('amatthewsq@gnu.org', 'Annie Matthews', '94171 Vera Pass', '0hA8vGPCV', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('kfreemanr@oakley.com', 'Karen Freeman', '6 Dottie Parkway', '5VoaKGAq9w', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('esmiths@google.co.jp', 'Emily Smith', '1361 Havey Terrace', '9SygwcSrKnU', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('crayt@amazon.co.jp', 'Christopher Ray', '0839 Grayhawk Hill', '5LdJ4GL15', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('jwagneru@bbb.org', 'James Wagner', '32 High Crossing Park', 'rqYQ6QYtu9QY', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('dhansonv@slate.com', 'Denise Hanson', '77534 Lakewood Plaza', 'mO2UpNUF', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('jcookw@phoca.cz', 'Jerry Cook', '31 Eliot Avenue', '31J9aokVEZxB', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('tbowmanx@hp.com', 'Theresa Bowman', '666 Corscot Lane', 'xYEzNGxw3uy3', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('pburkey@about.me', 'Peter Burke', '450 Thompson Drive', 'U5R43Wf', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('taustinz@java.com', 'Theresa Austin', '1 Michigan Avenue', 'Bh15dVyk', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('gfields10@unicef.org', 'Gerald Fields', '6 Donald Way', 'bm0rOydbo', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('dhart11@noaa.gov', 'Dorothy Hart', '7722 Spenser Road', 'HJNLvRQ', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('scastillo12@independent.co.uk', 'Stephanie Castillo', '1354 Stone Corner Street', '728dmPh', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('llittle13@google.cn', 'Laura Little', '27 Meadow Valley Pass', '62KOT7CuMch', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('jpeterson14@drupal.org', 'Johnny Peterson', '94000 Bartelt Center', 'MU6GRvTWTJ', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('jburton15@ifeng.com', 'Judith Burton', '28397 Hayes Hill', 'CG0AGC6AF', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('kking16@deviantart.com', 'Kelly King', '2606 Golf Course Trail', 'Fwo1JRK3AxV', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('jbanks17@reuters.com', 'Jimmy Banks', '89 Wayridge Court', 'KkrQSLNRcuJI', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('briley18@bandcamp.com', 'Bruce Riley', '69799 Kensington Lane', 'o5Kfb0W7X', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('aramirez19@qq.com', 'Angela Ramirez', '45 Cherokee Street', 'q82PeNk', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('tmendoza1a@guardian.co.uk', 'Teresa Mendoza', '818 Anderson Crossing', 'WcPKWEl76k', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('pmason1b@flickr.com', 'Phillip Mason', '615 Anhalt Circle', 'q1ZTEq6nPPhs', 'IN');
insert into "user" (email, nama, alamat, password, role) values ('cyoung1c@weebly.com', 'Christopher Young', '9036 Haas Plaza', 'PQxHAq', 'LA');
insert into "user" (email, nama, alamat, password, role) values ('cprice1d@engadget.com', 'Clarence Price', '3 Nobel Point', '3exsVhUg', 'IN');
