INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Bed','Babbleopia',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Bed','Feedspan',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Bed','Trudoo',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Aimbu',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Blogtags',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Feedbug',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Mikocok',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Ntag',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Realcube',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Skyba',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Sumsang',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','The Goods Dept',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Topicware',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Viva',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Handuk','Zoomzone',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','American Standard',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','Avavee',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','Blogtag',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','Bubbletube',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','Jabbersphere',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','Sumsang',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','Thoughtstorm',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung bantal','Tishoba',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung guling','Kwideo',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sarung guling','Tishoba',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Babbleset',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Centimia',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Devpoint',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Jaxspan',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Kanoodle',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Kazio',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Nlounge',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Realblab',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Realpoint',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Wikizz',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Wordtune',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Yamia',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Selimut','Zoovu',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Abata',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Brightbean',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Dazzlesphere',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Feednation',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Katz',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Mikocok',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Pixope',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Quimba',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Skipstorm',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','Tavu',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','The Goods Dept',0);
INSERT INTO INVENTORI(Nama,Merk,Stok) VALUES( 'Sprei','UNIQLO',0);