INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Sarung bantal','Sumsang',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Bed','Babbleopia',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Sarung bantal','American Standard',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Handuk','The Goods Dept',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Sprei','Dazzlesphere',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Bisnis','Sarung guling','Tishoba',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi AC','Sarung bantal','Sumsang',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi AC','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi AC','Bed','Trudoo',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi AC','Handuk','Topicware',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi AC','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi AC','Selimut','Wordtune',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi','Bed','Babbleopia',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi','Sarung bantal','American Standard',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi','Handuk','Mikocok',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi','Sprei','Katz',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Ekonomi','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Sarung bantal','Sumsang',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Sarung bantal','Blogtag',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Bed','Trudoo',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Handuk','Zoomzone',4);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Sprei','UNIQLO',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga AC','Selimut','Jaxspan',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Sarung bantal','Sumsang',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Sarung bantal','Tishoba',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Sarung guling','Tishoba',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Handuk','Skyba',4);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Sprei','UNIQLO',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Selimut','Babbleset',4);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Bisnis','Bed','Trudoo',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Ekonomi','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Ekonomi','Bed','Trudoo',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Ekonomi','Sarung bantal','Jabbersphere',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Ekonomi','Sprei','Feednation',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Ekonomi','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Keluarga Ekonomi','Selimut','Devpoint',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Sarung bantal','Sumsang',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Bed','Feedspan',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Sprei','The Goods Dept',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Sarung bantal','American Standard',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Sarung guling','Tishoba',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Selimut','Realblab',3);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Bisnis','Sprei','Abata',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi AC','Sprei','Mikocok',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi AC','Sarung bantal','Avavee',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi AC','Bed','Babbleopia',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi AC','Handuk','Zoomzone',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi AC','Sprei','UNIQLO',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi AC','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi AC','Selimut','Yamia',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi','Handuk','Feedbug',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi','Sprei','Brightbean',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi','Selimut','Wikizz',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi','Sarung bantal','American Standard',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Super Ekonomi','Bed','Babbleopia',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Sarung bantal','Sumsang',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Sprei','Pixope',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Handuk','Sumsang',4);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Sarung bantal','American Standard',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Sprei','UNIQLO',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Sprei','Skipstorm',1);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Sarung guling','Tishoba',2);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Selimut','Realpoint',3);
INSERT INTO INVENTORI_TIPE_KAMAR(NamaTipeKamar,NamaInventori,Merk,Jumlah) VALUES( 'Superior','Bed','Trudoo',1);
