INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Lori Williamson','46374 Tennyson Drive','lwilliamson0@gnu.org');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Tammy Evans','0 Lien Alley','tevans1@bloglovin.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Gloria Boyd','442 Duke Alley','gboyd2@ca.gov');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Adam Mcdonald','06 Rockefeller Point','amcdonald3@fc2.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Gregory Gutierrez','28 Little Fleur Alley','ggutierrez4@europa.eu');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Russell King','09039 Main Hill','rking5@wunderground.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Sandra Coleman','64602 Onsgard Plaza','scoleman6@webmd.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Patricia Reid','28523 Hauk Point','preid7@microsoft.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Billy Reed','46633 6th Crossing','breed8@diigo.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Charles Roberts','027 Lerdahl Circle','croberts9@nih.gov');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Robert Martin','94 Little Fleur Court','rmartina@unesco.org');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Arthur Franklin','92 Cherokee Street','afranklinb@github.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Craig Sanders','83827 Lakeland Lane','csandersc@prlog.org');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Judith Ortiz','92 Steensland Circle','jortizd@ucsd.edu');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Jerry Perkins','465 Towne Lane','jperkinse@sakura.ne.jp');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Ruby Dunn','850 Magdeline Junction','rdunnf@hexun.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Christina Rogers','9651 Armistice Circle','crogersg@walmart.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Gloria Warren','61 Schurz Center','gwarrenh@cloudflare.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Norma Moreno','2426 Express Circle','nmorenoi@ca.gov');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Ruth Dean','5 Arizona Avenue','rdeanj@tuttocitta.it');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Carol Watson','64 Debs Way','cwatsonk@ftc.gov');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Kathryn Gardner','36600 Montana Place','kgardnerl@trellian.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Jeremy Carr','8 Longview Place','jcarrm@flickr.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Irene Powell','50470 Maple Wood Terrace','ipowelln@blinklist.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Douglas Matthews','1 Linden Alley','dmatthewso@pinterest.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Gerald Roberts','884 Norway Maple Street','grobertsp@ucoz.ru');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Rachel Hansen','589 Northwestern Park','rhansenq@indiatimes.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Christine King','255 Monterey Road','ckingr@apple.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Clarence Coleman','7350 Pleasure Alley','ccolemans@vistaprint.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Frances Young','4 Brown Avenue','fyoungt@google.com.br');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Ernest Myers','87 Farragut Parkway','emyersu@google.co.uk');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Heather Flores','90 Sage Circle','hfloresv@abc.net.au');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Douglas Cook','125 Canary Avenue','dcookw@reddit.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Albert Rogers','048 Dapin Hill','arogersx@yale.edu');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Tina Castillo','13 Mariners Cove Lane','tcastilloy@deliciousdays.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Jose Robinson','75 Hansons Point','jrobinsonz@virginia.edu');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Kenneth Arnold','2151 American Park','karnold10@de.vu');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Anna Scott','44203 Saint Paul Park','ascott11@chronoengine.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Ruth Ellis','74475 Arapahoe Crossing','rellis12@hexun.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Brenda Sanders','91795 Florence Court','bsanders13@buzzfeed.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Bobby Cunningham','2220 South Center','bcunningham14@comcast.net');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Jason Gilbert','4300 Kenwood Crossing','jgilbert15@foxnews.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Annie Long','6318 Darwin Alley','along16@sitemeter.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Jimmy Morrison','0 Eagan Drive','jmorrison17@sakura.ne.jp');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'John Lane','296 Stang Point','jlane18@jimdo.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Laura Kelley','2 Petterle Parkway','lkelley19@360.cn');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Frank Hill','7 Carioca Alley','fhill1a@wisc.edu');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'John Davis','7 Lake View Alley','jdavis1b@shop-pro.jp');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Jean Flores','32 Luster Crossing','jflores1c@addthis.com');
INSERT INTO SUPPLIER(Nama,alamat,email) VALUES( 'Evelyn Clark','7 Memorial Park','eclark1d@free.fr');
