INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Bed','Babbleopia','rhart1@51.la','2016-2-5',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Bed','Feedspan','eross3@vk.com','2016-2-6',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Bed','Trudoo','jgray5@pcworld.com','2016-3-18',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Aimbu','tmyers7@slashdot.org','2016-3-19',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Blogtags','rsmith9@gnu.org','2016-3-20',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Feedbug','plopezb@google.com.au','2016-2-16',1,'berlubang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Mikocok','ecolemand@auda.org.au','2016-2-17',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Ntag','abishopf@mysql.com','2016-3-14',1,'hilang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Realcube','jhansenh@sun.com','2016-3-15',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Skyba','achapmanj@gizmodo.com','2016-3-16',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Sumsang','mtorresl@usgs.gov','2016-3-17',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','The Goods Dept','jmartinn@simplemachines.org','2016-3-18',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Topicware','jbrooksp@posterous.com','2016-2-18',1,'berlubang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Viva','kfreemanr@oakley.com','2016-2-25',1,'berlubang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Handuk','Zoomzone','crayt@amazon.co.jp','2016-2-26',1,'hilang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','American Standard','dhansonv@slate.com','2016-2-27',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','Avavee','tbowmanx@hp.com','2016-2-28',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','Blogtag','taustinz@java.com','2016-2-29',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','Bubbletube','dhart11@noaa.gov','2016-3-1',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','Jabbersphere','llittle13@google.cn','2016-3-2',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','Sumsang','jburton15@ifeng.com','2016-3-3',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','Thoughtstorm','aramirez19@qq.com','2016-3-4',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung bantal','Tishoba','pmason1b@flickr.com','2016-2-25',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung guling','Kwideo','cprice1d@engadget.com','2016-2-26',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sarung guling','Tishoba','jbanks17@reuters.com','2016-2-27',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Babbleset','rhart1@51.la','2016-2-7',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Centimia','eross3@vk.com','2016-2-8',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Devpoint','jgray5@pcworld.com','2016-3-20',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Jaxspan','tmyers7@slashdot.org','2016-3-21',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Kanoodle','rsmith9@gnu.org','2016-3-22',1,'berlubang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Kazio','plopezb@google.com.au','2016-2-18',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Nlounge','ecolemand@auda.org.au','2016-2-19',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Realblab','abishopf@mysql.com','2016-3-16',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Realpoint','jhansenh@sun.com','2016-3-17',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Wikizz','achapmanj@gizmodo.com','2016-3-18',1,'hilang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Wordtune','mtorresl@usgs.gov','2016-3-19',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Yamia','jmartinn@simplemachines.org','2016-3-20',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Selimut','Zoovu','jbrooksp@posterous.com','2016-2-20',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Abata','kfreemanr@oakley.com','2016-2-27',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Brightbean','crayt@amazon.co.jp','2016-2-28',1,'hilang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Dazzlesphere','dhansonv@slate.com','2016-2-29',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Feednation','tbowmanx@hp.com','2016-3-1',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Katz','taustinz@java.com','2016-3-2',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Mikocok','dhart11@noaa.gov','2016-3-3',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Pixope','llittle13@google.cn','2016-3-4',1,'hilang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Quimba','jburton15@ifeng.com','2016-3-5',1,'berlubang');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Skipstorm','aramirez19@qq.com','2016-3-6',1,'rusak');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','Tavu','pmason1b@flickr.com','2016-2-27',1,'terbakar');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','The Goods Dept','cprice1d@engadget.com','2016-2-28',1,'luntur');
INSERT INTO STAF_MENGGANTI_INVENTORI(nama,merk,emailStaf,waktu,jumlah,alasan) VALUES( 'Sprei','UNIQLO','jbanks17@reuters.com','2016-2-29',1,'berlubang');
