INSERT INTO tamu(id,nama,alamat) VALUES( 1,'William Flores','0 Derek Parkway');
INSERT INTO tamu(id,nama,alamat) VALUES( 2,'Margaret Butler','423 Carpenter Crossing');
INSERT INTO tamu(id,nama,alamat) VALUES( 3,'Adam Harris','9 Milwaukee Center');
INSERT INTO tamu(id,nama,alamat) VALUES( 4,'Todd Black','72743 Forest Dale Junction');
INSERT INTO tamu(id,nama,alamat) VALUES( 5,'Brian Walker','72325 Crescent Oaks Street');
INSERT INTO tamu(id,nama,alamat) VALUES( 6,'Janet Davis','6528 Hanson Street');
INSERT INTO tamu(id,nama,alamat) VALUES( 7,'Clarence Jacobs','147 Steensland Alley');
INSERT INTO tamu(id,nama,alamat) VALUES( 8,'Johnny Thompson','19 Oak Valley Trail');
INSERT INTO tamu(id,nama,alamat) VALUES( 9,'Scott Price','85 Montana Point');
INSERT INTO tamu(id,nama,alamat) VALUES( 10,'Sarah Alexander','04 Shopko Alley');
INSERT INTO tamu(id,nama,alamat) VALUES( 11,'Anna Harper','1 Prairieview Pass');
INSERT INTO tamu(id,nama,alamat) VALUES( 12,'Angela Young','3 New Castle Pass');
INSERT INTO tamu(id,nama,alamat) VALUES( 13,'Theresa Jordan','2 Huxley Point');
INSERT INTO tamu(id,nama,alamat) VALUES( 14,'Melissa Williams','03 Katie Terrace');
INSERT INTO tamu(id,nama,alamat) VALUES( 15,'Catherine Scott','904 Pepper Wood Circle');
INSERT INTO tamu(id,nama,alamat) VALUES( 16,'Carlos Rodriguez','01614 Bayside Pass');
INSERT INTO tamu(id,nama,alamat) VALUES( 17,'Walter Tucker','8430 Sachs Avenue');
INSERT INTO tamu(id,nama,alamat) VALUES( 18,'Margaret Johnston','35 Everett Court');
INSERT INTO tamu(id,nama,alamat) VALUES( 19,'Ralph Vasquez','105 Coleman Road');
INSERT INTO tamu(id,nama,alamat) VALUES( 20,'Catherine Robertson','49 Logan Terrace');
INSERT INTO tamu(id,nama,alamat) VALUES( 21,'Nicole Rogers','43 Homewood Avenue');
INSERT INTO tamu(id,nama,alamat) VALUES( 22,'Ernest Hicks','05967 Bartelt Terrace');
INSERT INTO tamu(id,nama,alamat) VALUES( 23,'Amanda Davis','5573 Lakewood Avenue');
INSERT INTO tamu(id,nama,alamat) VALUES( 24,'Frank Nguyen','8 Arizona Plaza');
INSERT INTO tamu(id,nama,alamat) VALUES( 25,'Steve Riley','9 Hooker Circle');
INSERT INTO tamu(id,nama,alamat) VALUES( 26,'Nicole Martin','199 Jenifer Court');
INSERT INTO tamu(id,nama,alamat) VALUES( 27,'Eugene Bryant','00991 6th Drive');
INSERT INTO tamu(id,nama,alamat) VALUES( 28,'Lisa Cox','772 Schurz Court');
INSERT INTO tamu(id,nama,alamat) VALUES( 29,'Timothy Lopez','910 South Lane');
INSERT INTO tamu(id,nama,alamat) VALUES( 30,'Angela Owens','2727 Eastwood Parkway');
INSERT INTO tamu(id,nama,alamat) VALUES( 31,'Willie Holmes','50269 Kings Trail');
INSERT INTO tamu(id,nama,alamat) VALUES( 32,'Evelyn Franklin','9145 Chive Crossing');
INSERT INTO tamu(id,nama,alamat) VALUES( 33,'Julie Garrett','8 8th Way');
INSERT INTO tamu(id,nama,alamat) VALUES( 34,'Kathy Cole','12877 Caliangt Pass');
INSERT INTO tamu(id,nama,alamat) VALUES( 35,'Teresa Porter','1665 Esker Park');
INSERT INTO tamu(id,nama,alamat) VALUES( 36,'Raymond Ellis','37 Cordelia Drive');
INSERT INTO tamu(id,nama,alamat) VALUES( 37,'Wayne Perkins','69 Havey Way');
INSERT INTO tamu(id,nama,alamat) VALUES( 38,'Brandon Mcdonald','43335 Stephen Junction');
INSERT INTO tamu(id,nama,alamat) VALUES( 39,'Johnny Griffin','82872 Ronald Regan Road');
INSERT INTO tamu(id,nama,alamat) VALUES( 40,'Kelly Bowman','59 Holmberg Road');
INSERT INTO tamu(id,nama,alamat) VALUES( 41,'Steven Hernandez','929 Arkansas Trail');
INSERT INTO tamu(id,nama,alamat) VALUES( 42,'Barbara Stone','74 Hanover Avenue');
INSERT INTO tamu(id,nama,alamat) VALUES( 43,'Susan Harrison','02 Loftsgordon Lane');
INSERT INTO tamu(id,nama,alamat) VALUES( 44,'Steven Ortiz','3172 Lien Trail');
INSERT INTO tamu(id,nama,alamat) VALUES( 45,'Ernest Young','9 Tomscot Point');
INSERT INTO tamu(id,nama,alamat) VALUES( 46,'Tammy Wagner','80162 Merchant Lane');
INSERT INTO tamu(id,nama,alamat) VALUES( 47,'James Hunt','86 Scofield Crossing');
INSERT INTO tamu(id,nama,alamat) VALUES( 48,'Earl Jacobs','6521 Weeping Birch Avenue');
INSERT INTO tamu(id,nama,alamat) VALUES( 49,'Christina Rose','06 Reindahl Hill');
INSERT INTO tamu(id,nama,alamat) VALUES( 50,'Anne Austin','9256 Autumn Leaf Parkway');
