INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 1,1,'Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 2,1,'Super Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 3,1,'Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 4,1,'Super Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 5,1,'Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 6,1,'Super Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 7,1,'Keluarga Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 8,1,'Keluarga AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 9,1,'Keluarga Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 10,1,'Superior');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 1,2,'Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 2,2,'Super Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 3,2,'Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 4,2,'Super Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 5,2,'Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 6,2,'Super Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 7,2,'Keluarga Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 8,2,'Keluarga AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 9,2,'Keluarga Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 10,2,'Superior');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 1,3,'Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 2,3,'Super Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 3,3,'Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 4,3,'Super Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 5,3,'Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 6,3,'Super Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 7,3,'Keluarga Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 8,3,'Keluarga AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 9,3,'Keluarga Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 10,3,'Superior');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 1,4,'Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 2,4,'Super Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 3,4,'Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 4,4,'Super Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 5,4,'Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 6,4,'Super Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 7,4,'Keluarga Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 8,4,'Keluarga AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 9,4,'Keluarga Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 10,4,'Superior');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 1,5,'Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 2,5,'Super Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 3,5,'Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 4,5,'Super Ekonomi AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 5,5,'Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 6,5,'Super Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 7,5,'Keluarga Ekonomi');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 8,5,'Keluarga AC');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 9,5,'Keluarga Bisnis');
INSERT INTO kamar(nomor,lantai,namaTipeKamar) VALUES( 10,5,'Superior');
